services:
  spirit:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file: app/config/.env

  postgres:
    image: "postgres:latest"
    restart: unless-stopped
    env_file: app/config/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    restart: unless-stopped
    env_file: app/config/.env
    ports:
      - "6389:6379"

volumes:
  postgres-data:
