services:
  spirit: &spirit
    container_name: spirit
    restart: unless-stopped
    command:
      - scripts/dev-server-bot.sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/old
    env_file: config/env/.env
#    networks:
#      - spirit_network

#  spirit-backend:
#    container_name: spirit-backend
#    <<: *spirit
#    restart: unless-stopped
#    command:
##      - python manage.py runserver 0.0.0.0:8000
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/old
#    env_file: old/config/.env
#    networks:
#      - spirit_network
#
#  postgres:
#    container_name: postgres
#    image: "postgres:latest"
#    restart: unless-stopped
#    env_file: old/config/.env
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - spirit_network
#
#  redis:
#    container_name: redis
#    image: "redis:latest"
#    restart: unless-stopped
#    env_file: old/config/.env
#    ports:
#      - "6389:6379"
#    networks:
#      - spirit_network
#
#volumes:
#  postgres-data:
#
#networks:
#  spirit_network:
