[project]
name = "spirit"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
  "accelerate==1.5.2",
  "aiogram==3.22.0",
  "aioinject==0.38.0",
  "apscheduler==4.0.0a5",
  "backoff==2.2.1",
  "celery==5.4.0",
  "django==5.2.6",
  "django-ninja==1.3.0",
  "django-redis>=6.0.0",
  "httpx==0.28.1",
  "loguru==0.7.3",
  "msgspec==0.19.0",
  "psycopg>=3.2.10",
  "pytz==2025.1",
  "rq==2.6.0",
  "torch==2.8.0",
  "transformers==4.56.1",
]


[dependency-groups]
dev = [
  "ipython>=9.5.0",
  "ipywidgets>=8.1.7",
  "jupyter>=1.1.1",
  "mypy>=1.17.1",
  "pytest>=8.4.2",
  "pytest-mock>=3.15.0",
  "pytest-randomly>=3.16.0",
  "ruff>=0.12.12",
]

[tool.pytest.ini_options]
norecursedirs = "*.egg .eggs .* dist build docs .tox .git __pycache__ etc"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
addopts = [
  "--import-mode=importlib",
  "--strict-markers",
  "--strict-config",
  "--tb=short",
]
filterwarnings = [
  "ignore::DeprecationWarning:pytest_freezegun:17",
]


[tool.ruff]
lint.select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "B", # flake-bugbear
  "Q", # flake8-quotes
  "I", # isort
  "S", # flake8-bandit
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "C4", # flake8-comprehensions
  "PIE", # flake8-pie
  "TRY", # tryceratops
  "RUF", # ruff
  "PL", # pylint
  "DTZ", # flake8-datetimez
  "UP", # pyupgrade
  "C90", # mccabe
  "COM", # flake8-commas
  "INP", # flake8-no-pep420
  "TID", # flake8-tidy-imports
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
  "EM", # flake8-errmsg
  "FA", # flake8-future-annotations
  "PERF", # Perflint
  "PYI" # flake8-pyi
]

lint.ignore = [
  "E501", # Never enforce line length
  "RET504", # Unnecessary variable assignment before `return` statement
  "RUF001", # ruff unicode specific rules
  "RUF002", # ruff unicode specific rules
  "RUF003", # ruff unicode specific rules
  "TRY003", # Duplicates EM101 warning
  "B904", # Duplicates B904 warning
  'COM812'
]

lint.unfixable = [
  "B", # Avoid trying to fix flake8-bugbear violations.
  "ERA", # Avoid deleting commented-out code
]

line-length = 90
target-version = "py311"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "ARG001", # Unused function argument
  "ARG002", # Unused method argument
  "ERA001", # Found commented-out code
  "PLR0913", # Too many arguments to function call
  "PLR2004", # Magic value used in comparison
  "S101", # Use of `assert` detected
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true


[tool.mypy]
plugins = ["pydantic.mypy"]

strict = true
follow_imports = "normal"
ignore_missing_imports = true

allow_redefinition = false
disallow_any_explicit = false
ignore_errors = false
local_partial_types = true
no_implicit_optional = true
strict_optional = true
warn_no_return = true
warn_return_any = false
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true

[tool.pydantic-mypy]
init_forbid_extra = false
init_typed = false
warn_required_dynamic_aliases = true
