[tool.poetry]
name = "spirit"
version = "0.1.0"
description = ""
authors = ["NickiHell <nickihell@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

torch = "^1.13.1"
transformers = "^4.26.1"
bitsandbytes = "^0.39.1"
aiogram = "^2.25.1"
loguru = "^0.7.0"
black = "^23.1.0"
ruff = "^0.0.275"

[tool.ruff]
select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "B", # flake-bugbear
  "Q", # flake8-quotes
  "I", # isort
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "FBT", # flake8-boolean-trap
  "C4", # flake8-comprehensions
  "PIE", # flake8-pie
  "TRY", # tryceratops
  "RUF", # ruff
  "PL", # pylint
  "UP", # pyupgrade
  "C90", # mccabe
  "COM", # flake8-commas
  "INP", # flake8-no-pep420
  "TID", # flake8-tidy-imports
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
  "EM", # flake8-errmsg
  "FA", # flake8-future-annotations
]

ignore = [
  "E501", # Never enforce line length
  "RET504", # Unnecessary variable assignment before `return` statement
  "RUF001", # ruff unicode specific rules
  "RUF002", # ruff unicode specific rules
  "RUF003", # ruff unicode specific rules
  "TRY200", # Duplicates B904 warning
]

unfixable = [
  "B", # Avoid trying to fix flake8-bugbear violations.
  "ERA", # Avoid deleting commented-out code
]

line-length = 140
target-version = "py311"

[tool.ruff.per-file-ignores]
"*/settings/*" = [
  "ERA001", # Found commented-out code
  "PLW1508", # Invalid type for environment variable default
  "FBT003", # Boolean positional value in function call
]
"tests/*" = [
  "ARG001", # Unused function argument
  "ARG002", # Unused method argument
  "ERA001", # Found commented-out code
  "PLR0913", # Too many arguments to function call
  "PLR2004", # Magic value used in comparison
  "INP001", # File is part of an implicit namespace package
]
"*/migrations/*" = [
  "INP001", # Add an `__init__.py`
  "ERA001", # Found commented-out code
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["ninja.Query"]

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.isort]
lines-after-imports = 2


[tool.black]
line-length = 90
target-version = ["py311"]
skip-string-normalization = true
exclude = ".git/|media/"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "image_service.settings"
norecursedirs = "*.egg .eggs .* dist build docs __pycache__ etc"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
addopts = [
  "--import-mode=importlib",
  "--strict-markers",
  "--strict-config",
  "--tb=short",
]
filterwarnings = [
  "ignore::DeprecationWarning:pytest_freezegun:17",
  "ignore::DeprecationWarning:concurrency.config:71",
  "ignore::DeprecationWarning:celery.utils.imports:145",
  "ignore::DeprecationWarning:kombu.utils.compat:82",
]


[tool.mypy]
plugins = ["pydantic.mypy"]

allow_redefinition = false
check_untyped_defs = true
disallow_untyped_decorators = true
disallow_any_explicit = false
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = true
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
follow_imports = "silent"
pretty = true
show_error_codes = true
show_column_numbers = true

[[tool.mypy.overrides]]
disallow_incomplete_defs = false

[tool.pydantic-mypy]
init_forbid_extra = false
init_typed = false
warn_required_dynamic_aliases = true
warn_untyped_fields = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
