# Generated by Django 5.2.6 on 2025-09-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False, verbose_name='Bot is running')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Last error')),
            ],
            options={
                'verbose_name': 'Bot status',
                'verbose_name_plural': 'Bot status',
            },
        ),
        migrations.CreateModel(
            name='ResponseStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('strategy_type', models.CharField(choices=[('keyword', 'Keyword-based'), ('regex', 'Regex-based'), ('vikhr', 'Vikhr-Nemo LLM-based')], max_length=20, verbose_name='Strategy type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('keyword', models.CharField(blank=True, default='', max_length=255, verbose_name='Keyword')),
                ('case_sensitive', models.BooleanField(default=False, verbose_name='Case sensitive')),
                ('regex_pattern', models.CharField(blank=True, default='', max_length=500, verbose_name='Regex pattern')),
                ('max_length', models.IntegerField(default=512, help_text='Maximum length of generated response', verbose_name='Max response length')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature parameter for generation (higher value means more creative response)', verbose_name='Temperature')),
                ('response_template', models.TextField(verbose_name='Response template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Response strategy',
                'verbose_name_plural': 'Response strategies',
                'ordering': ['-priority'],
            },
        ),
    ]
